image: ruby:2.4.2
stages:
  - build
  - test
  - review
  - stage
  - production

variables:
 DATABASE_URL: 'mongodb://mongo/user_posts'
 DOCKER_IMAGE: "torchun/otus-reddit"

services:
  - docker:dind

before_script:
  - cd reddit
  - bundle install

build_job:
  stage: build
  image: docker
  variables:
    #  because of docker-in-docker
    #  DOCKER_HOST: tcp://docker:2375
    DOCKER_TLS_CERTDIR: ""
    DOCKER_DRIVER: overlay2
  # Added docker build
  # git commit -am "show GitLab $ENV" && git push gitlab gitlab-ci-1
  before_script:
    - docker info
    - echo "before_script finished"
  script:
    - echo 'Building'
    - echo $ENV

#test_unit_job:
#  stage: test
#  script:
#    - echo 'Testing 1'

test_unit_job:
  stage: test
  services:
    - mongo:latest
  script:
    - ruby simpletest.rb

test_integration_job:
  stage: test
  script:
    - echo 'Testing 2'

deploy_dev_job:
  stage: review
  script:
    - echo 'Deploy'
  environment:
    name: dev
    url: http://dev.example.com

branch review:
  stage: review
  script: echo "Deploy to $CI_ENVIRONMENT_SLUG"
  environment:
    name: branch/$CI_COMMIT_REF_NAME
    url: http://$CI_ENVIRONMENT_SLUG.example.com
  only:
    - branches
  except:
    - master

staging:
  stage: stage
  when: manual
  only:
   - /^\d+\.\d+\.\d+/
  script:
    - echo 'Deploy stage'
  environment:
    name: beta
    url: http://beta.example.com

production:
  stage: production
  when: manual
  script:
    - echo 'Deploy prod'
  environment:
    name: production
    url: http://example.com
