dist: trusty
sudo: required
language: bash
before_install:
- curl https://raw.githubusercontent.com/express42/otus-homeworks/2020-11/run.sh | bash
- sudo apt-get update
- sudo apt-get install pip
- sudo pip install ansible==2.10.3
- sudo pip install ansible-lint
notifications:
  slack:
    rooms:
      secure: aMNtqaA31A2g83vkAYZNOoWtnp//D1HjprIz4W4pGNXmXyqdy1MnGnu7WoS9I+RoVOqzttIXGIv1eiPxaA7caJo79bJXJ37oWvbUsTMGEk3K+HQZneLtTM0bUpeP4pc9Qejnj61gkQHL3uRlYkzVL9NBqBs1j+RRwGa8ms5kVVer/3mDRgX4iYbkZyCD6fZQFZhZ0s32ZiknQZlXBriSObG3itXhjjXVCEcBiyn2j4tLJrMHsvNS2jsI9KICxz+IlJQG62L8ZC1Y4aQXfACXWNVTzeLFhGeRWrXe1Bpgvf7XUqtbkrWxTP2I8ECysMLVFrIBZ0hG9Lr6fNkTyHvxy+MTbDIHjg5R+Q/+QJrfP0AwcIkw/YqC43NFx2P24ErISlbBO7Ozs69aVawak2pEZHXYWgJAYU5RORaOz9JEHRnEAuccyC4dvVA6s6u/dxzB0ER7CiET3IXfEGLxILFfLXKP8Yfnl5BjKz7w15giiD9nvd9T0AhIIxqZLDJGBBcMcsleOA7LQSZdJj/ibCitF4r8xhfPZgTObgGjqNOgnqAXCUuFtkrnNI86gd4ds66vmheViaf8EeZq079TKPpNesIAeONr3HHqLAf1zwM9Fn05TBiTKU1QTduAZ65fu5qFc+B5L9h6dbVXjeHTMSaWYPM1AuxG50ziu8gf+bzv54Y=
