---
- name: configure directories to be used by docker
  hosts: gitlab
  become: true
  tasks:
  - name: Create directories
    become: true
    ansible.builtin.file:
      path: "{{ item }}"
      state: directory
      recurse: yes
      owner: root
      group: root
    loop:
      - /srv/gitlab/config
      - /srv/gitlab/logs
      - /srv/gitlab/data
      - /srv/gitlabrunner/config

#  - name: Grant +rw premissions recursively
#    become: true
#    ansible.builtin.file:
#      dest: /srv
#      owner: ubuntu
#      group: ubuntu
#      mode: u=rwX,g=rX,o=rX
#      recurse: yes

  - name: Debug vars
    debug:
      msg: "external_url http://{{ item }}"
    with_items: "{{ groups['gitlab'] }}"

  - name: Start gitlab docker
    community.general.docker_container:
      name: gitlab
      image: gitlab/gitlab-ce:latest
      restart_policy: always
      env:
        GITLAB_OMNIBUS_CONFIG: "external_url 'http://{{ item }}'"
      state: started
      ports:
        - "80:80"
        - "443:443"
        - "2222:22"
      volumes:
        - /srv/gitlab/config:/etc/gitlab
        - /srv/gitlab/logs:/var/log/gitlab
        - /srv/gitlab/data:/var/opt/gitlab
    with_items: "{{ groups['gitlab'] }}"
