---
- name: install ruby
  hosts: all
  become: true

  roles:
    - app

### removed
#  tasks:
#    - name: install ruby
#      apt:
#        name:
#          - ruby-full
#          - ruby-bundler
#          - build-essential
#        update_cache: yes
#        state: present
