- name: Deploy App
  hosts: app
  tags: deploy-tag
  tasks:
    - name: install git
      become: yes
      apt: name=git state=present
      retries: 10
      delay: 10 # in seconds
      register: result
      until: result is not failed
#    - debug:
#        msg: "{{result}}"
#
#        "msg": {
#          "cache_update_time": 1609237469,
#          "cache_updated": false,
#          "changed": false,
#          "failed": false
#        }

    - name: Fetch the latest version of application code
      git:
        repo: 'https://github.com/express42/reddit.git'
        dest: /home/ubuntu/reddit
        version: monolith
      notify: restart puma

    - name: bundle install
      bundler:
        state: present
        chdir: /home/ubuntu/reddit

  handlers:
  - name: restart puma
    become: true
    systemd: name=puma state=restarted
